// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK5yD55OhDSoxZ4fP_Gm34e7iwCAms1tE',
    appId: '1:219553067194:web:0ddfc0fafedbc42fd91283',
    messagingSenderId: '219553067194',
    projectId: 'linea-d4f72',
    authDomain: 'linea-d4f72.firebaseapp.com',
    storageBucket: 'linea-d4f72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyvDl-dST7MKluGJQZ3n1lcwIg3jFGbxM',
    appId: '1:219553067194:android:e6d33d4cb86f67c9d91283',
    messagingSenderId: '219553067194',
    projectId: 'linea-d4f72',
    storageBucket: 'linea-d4f72.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK5yD55OhDSoxZ4fP_Gm34e7iwCAms1tE',
    appId: '1:219553067194:web:8623edc2657a3324d91283',
    messagingSenderId: '219553067194',
    projectId: 'linea-d4f72',
    authDomain: 'linea-d4f72.firebaseapp.com',
    storageBucket: 'linea-d4f72.firebasestorage.app',
  );
}
